In [20]:
import numpy as np
import pandas as pd
import datetime

In [4]:
date = pd.read_csv('orders.csv')
time = pd.read_csv('messages.csv')

In [5]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [6]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [7]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [8]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [9]:
date['date'] = pd.to_datetime(date['date'])

In [10]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

In [11]:
date.head()

        date  product_id  city_id  orders
0 2019-12-10        5628       25       3
1 2018-08-15        3646       14     157
2 2018-10-23        1859       25       1
3 2019-08-17        7292       25       1
4 2019-01-06        4344       25       3

In [12]:
date['date_year'] = date['date'].dt.year

In [13]:
date.sample(4)

          date  product_id  city_id  orders  date_year
115 2018-10-13        5779       13       6       2018
284 2018-07-27        3635       16      48       2018
675 2018-12-05        4038       27       1       2018
817 2019-10-20        3271        0       1       2019

In [15]:
date['date_month'] = date['date'].dt.month

In [18]:
date.sample(5)

          date  product_id  city_id  orders  date_year  date_month
740 2019-08-05         709       16     220       2019           8
748 2019-01-12         920       14       1       2019           1
184 2019-01-21        6371        7       8       2019           1
614 2018-08-14        5941       25       2       2018           8
990 2018-10-28        3034        0       1       2018          10

In [19]:
date['quarter'] = date['date'].dt.quarter

date.drop(columns=['product_id','city_id','orders']).head()

        date  date_year  date_month  quarter
0 2019-12-10       2019          12        4
1 2018-08-15       2018           8        3
2 2018-10-23       2018          10        4
3 2019-08-17       2019           8        3
4 2019-01-06       2019           1        1

In [21]:
today = datetime.datetime.today()

today

datetime.datetime(2026, 10, 23, 21, 37, 55, 204706)

In [22]:
today - date['date']

0     2509 days 21:37:55.204706
1     2991 days 21:37:55.204706
2     2922 days 21:37:55.204706
3     2624 days 21:37:55.204706
4     2847 days 21:37:55.204706
                 ...
995   2937 days 21:37:55.204706
996   2878 days 21:37:55.204706
997   2726 days 21:37:55.204706
998   2791 days 21:37:55.204706
999   2565 days 21:37:55.204706
Name: date, Length: 1000, dtype: timedelta64[ns]

In [23]:
time['hour'] = time['date'].dt.hour
time['min'] = time['date'].dt.minute
time['sec'] = time['date'].dt.second

time.head()

AttributeError: Can only use .dt accessor with datetimelike values

In [24]:
# in seconds

(today - time['date'])/np.timedelta64(1,'s')

TypeError: unsupported operand type(s) for -: 'Timestamp' and 'str'